sudo: required
services:
   - docker

before_install:
   - docker build -t mgarciac88/react-test -f ./client/Dockerfile.dev ./client

script:
   - docker run -e CI=true mgarciac88/react-test npm test

after_success:
   - docker build -t mgarciac88/multi-client ./client
   - docker build -t mgarciac88/multi-nginx ./nginx
   - docker build -t mgarciac88/multi-server ./server
   - docker build -t mgarciac88/multi-worker ./worker

# Log in into the docker CLI
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take the images ans push them to docker hub..
- docker push mgarciac88/multi-client
- docker push mgarciac88/multi-nginx
- docker push mgarciac88/multi-server
- docker push mgarciac88/multi-worker

